# Generated by Django 4.1.7 on 2023-03-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Gjfjk',
        ),
    ]
