# Generated by Django 4.1.7 on 2023-03-07 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='дата')),
                ('order_sum', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма заказа')),
                ('user_id', models.ManyToManyField(to='user.user')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
